name: Build binaries

on:
    push:
        paths-ignore:
        - 'README.md'
        - 'CHANGELOG.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up build environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.15

      - name: Library dependencies
        run: sudo apt-get install libmpv-dev libglx-dev libgl-dev

      - name: Compile
        run: |
          go get .
          go build .

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: stmp
